### ISSUE TITLE
[Bug]: 2.1.6 don't load tasks, only play animation

### ISSUE THREAD

**Issue by ropbl4** [MrDavidRios/remindr_releases#10]
### What went wrong?

2.1.6 don't load tasks, only play animation.
![image](https://github.com/MrDavidRios/remindr_releases/assets/71985019/fe8c737a-b71e-4e5e-a149-37e682923bc7)

### Version

2.1.6

### Operating System

Win

### Additional information

2.1.5 works good.

**Comment by MrDavidRios** [comment]
Sorry, I was a bit careless in testing my latest changed -- I improved some online database syncing code and broke offline functionality in the process; a fix will be out soon.

**Comment by MrDavidRios** [comment]
Should be fixed in the latest release ([2.1.7](https://github.com/MrDavidRios/remindr_releases/releases/tag/v2.1.7)) - feel free to reopen this issue if it isn't fixed on your end.
