### ISSUE TITLE
[Bug]: Messed up calendar on the latest version

### ISSUE THREAD

**Issue by etherealxx** [MrDavidRios/remindr_releases#11]
### What went wrong?

Every month 1st comes on sunday, on every year

### Version

2.1.7

### Operating System

Windows 11

### Additional information

![image](https://github.com/MrDavidRios/remindr_releases/assets/64251396/1f8254fd-d2d1-4ecd-be76-feade7368ee3)

**Comment by MrDavidRios** [comment]
This is most likely an update error in settings values -- when introducing the 'first day of week' setting, Remindr probably didn't automatically add a default settings value, leaving it undefined (and breaking the calendar).

If you go to **_Settings > General > First Day of Week_** and select the day for start of week (e.g. Sunday) it should be fixed.

Let me know if this doesn't work!

**Comment by etherealxx** [comment]
Works now so far, thanks.
