### ISSUE TITLE
[Bug]: 2.1.8 Black Screen

### ISSUE THREAD

**Issue by MonolithOrchids** [MrDavidRios/remindr_releases#12]
### What went wrong?

Hello, the newest 2.1.8 doesn't work, it just open a black screen, unable to do anything.
If I downgrade to 2.1.7 it will work until the next restart since it will auto update to 2.1.8.

### Version

2.1.8

### Operating System

Windows 10 x64

**Comment by MrDavidRios** [comment]
Sorry to hear that; I'll undo the update until I'm able to fix it, since this seems like something that's not going to affect only you.

I'll work on recreating the bug.

**Comment by MrDavidRios** [comment]
The app should be working as normal now — a tiny bug brought down the whole app. I'll close the issue when I get confirmation that 2.1.8 works for you.

Thanks for letting me know!
