### ISSUE TITLE
[Bug]: Can't update and even install v2.1.11

### ISSUE THREAD

**Issue by ropbl4** [MrDavidRios/remindr_releases#15]
### What went wrong?

If i press "Update" in Remindr - error:
"Can't delete old application files.
Please try run installer again.: 2"
and all files (except uninstaller) have been deleted.

![image](https://github.com/MrDavidRios/remindr_releases/assets/71985019/14420d31-92b8-4c53-a915-85b1dea0d30c)

I download installer v2.1.11 and try to install - error:
"Windows need file Remindr.exe.
To find it yourself press Explore...",
but i don't have this file, because Remindr delete it.

I install previous version, copy Remindr.exe and try to update:
updater delete it again and can't run.

I have no ideas, how can i update ))

### Version

2.1.10-2.1.11

### Operating System

Win

**Comment by MrDavidRios** [comment]
Thanks for your patience in dealing with and reporting all of these bugs — it's a huge help. This seems to be a bug with electron-builder, which I'm using to package Remindr; it's not installing the app at _all_. I'll continue working on a fix throughout the next few days.

**Comment by MrDavidRios** [comment]
Both issues are fixed. The installer for v2.1.11 now works and v2.1.12 now updates properly — this error won't pop up again when updating to v2.1.13 and on.
