### ISSUE TITLE
Could not Create Account

### ISSUE THREAD

**Issue by JiashunLi** [MrDavidRios/remindr_releases#2]
I can't create a account br=efore login on,
Maybe I can't arrive the website because I'm in china
![image](https://user-images.githubusercontent.com/38833358/147829650-687f52ce-4aba-49c9-8544-2a95a17a213a.png)

**Comment by MrDavidRios** [comment]
Yes, I'm sorry to say that Remindr uses Firebase services (Authentication, Firestore, Storage) to manage accounts/online data and most Firebase services don't seem to work well in China, since the *.google.com URL is blocked and Firebase depends on it.
