### ISSUE TITLE
Settings don't save.

### ISSUE THREAD

**Issue by ropbl4** [MrDavidRios/remindr_releases#4]
Settings don't save.
Starts from v.2.0 settings don't save.
I change settings, click checkboxes... then click upper-right cross (don't have "Save" button) - no effect, open Settings again and all changes doesn't save.
Windows 10.

**Comment by etherealxx** [comment]
Replicable
![ezgif com-video-to-gif](https://github.com/MrDavidRios/remindr_releases/assets/64251396/8f429396-47a6-4fcb-9cc8-ce880f99ecde)

**Comment by MrDavidRios** [comment]
Thanks for making a recording @etherealxx; I'm only able to reproduce the bug for the 'hide window when launched on startup' setting. Is this happening for all other settings?

**Comment by ropbl4** [comment]
>  Is this happening for all other settings?

Yes.

**Comment by MrDavidRios** [comment]
Was able to recreate it on my end and fix it locally; let me know if the new version fixes it for you too

**Comment by etherealxx** [comment]
Yes, the newest version 2.0.2 fixed it.
