### ISSUE TITLE
[Bug] Newest release unable to make any reminder

### ISSUE THREAD

**Issue by etherealxx** [MrDavidRios/remindr_releases#5]
the context is, i just updated it from the update popup.

![ezgif com-video-to-gif (1)](https://github.com/MrDavidRios/remindr_releases/assets/64251396/597c2997-2513-45f9-8aba-d8fdbfe4ac98)

**Comment by etherealxx** [comment]
Update:
I tried installing and uninstalling several version. The latest version i got it to works is 2.0.2

**Comment by MrDavidRios** [comment]
It seems like the menu doesn't work if animations are disabled. Would you mind trying with animations enabled?

I'll release a fix for that soon - thanks for catching that

**Comment by MrDavidRios** [comment]
[This release](https://github.com/MrDavidRios/remindr_releases/releases/tag/v2.1.2) should fix it
