### ISSUE TITLE
No red dot on tray badge

### ISSUE THREAD

**Issue by ropbl4** [MrDavidRios/remindr_releases#7]
No red dot on tray badge on overdoed task,
without red dot i can forget about my task.
It starts approximately after v2.1.0

![Remindr bug 03](https://github.com/MrDavidRios/remindr_releases/assets/71985019/1dc3841b-fa88-48bd-bdf2-c054fd500ec3)
![Remindr bug 04](https://github.com/MrDavidRios/remindr_releases/assets/71985019/17d9a15f-75ba-46c8-b4b8-6a24dce90c63)

**Comment by MrDavidRios** [comment]
Just to be completely sure this is a bug, are the task badge settings enabled?
![image](https://github.com/MrDavidRios/remindr_releases/assets/52746497/4c89fa88-f2ad-42e7-bc12-781c515db7ce)

**Comment by ropbl4** [comment]
I don't have that settings -___-
![image](https://github.com/MrDavidRios/remindr_releases/assets/71985019/d1c45222-45e3-4eaf-9c22-d1dbd90fdd95)
Starts approximately after v2.0

**Comment by MrDavidRios** [comment]
You should [now](https://github.com/MrDavidRios/remindr_releases/releases/tag/v2.1.3) be able to see those settings.
