### ISSUE TITLE
Move Sunday to right side of calendar

### ISSUE THREAD

**Issue by ropbl4** [MrDavidRios/remindr_releases#9]
Can you add option:
move Sunday to right side of calendar (week starts from Monday) ?

![0](https://github.com/MrDavidRios/remindr_releases/assets/71985019/90b13708-975b-430a-b453-a47377146acd)

**Comment by MrDavidRios** [comment]
Good idea; I'll work on this for the next update.

It will be an option to let you select any day of the week as the 'start of week'.

**Comment by MrDavidRios** [comment]
It's part of the [latest release](https://github.com/MrDavidRios/remindr_releases/releases/tag/v2.1.5); let me know if anything doesn't work as expected!
